server:
  port: 8888

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/AdmerkCorp
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update

application:
  security:
    jwt:
      secret-key: wiHpgJV9Is0zQRcsQYuOfVblNxfXkU4z6JquCyd4INV
      expiration: 60000 # 86400000 # a day
      refresh-token:
        expiration: 604800000 # 7 days