server:
  port: 8888

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/AdmerkCorp
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false

application:
  security:
    jwt:
      secret-key: wiHpgJV9Is0zQRcsQYuOfVblNxfXkU4z6JquCyd4INV
      expiration: 604800000 # 7 days
      refresh-token:
        expiration: 604800000 # 7 days

upload:
  directory:
    cv: G:/AdmerkCorp.com/CVs
    profilePicture: G:/AdmerkCorp.com/ProfilePictures
