package com.AdmerkCorp.model.job;


public enum Category {

    ACCOUNTING, ADMINISTRATIVE, ADVERTISING, AGRICULTURE, ARTS_AND_DESIGN, BANKING, BIOTECHNOLOGY,
    BUSINESS_DEVELOPMENT, CONSULTING, CUSTOMER_SERVICE, EDUCATION, ENGINEERING, FINANCE, HEALTHCARE,
    HUMAN_RESOURCES, INFORMATION_TECHNOLOGY, LEGAL, MANUFACTURING, MARKETING, MEDIA_AND_COMMUNICATIONS,
    NONPROFIT, RETAIL, SALES, SCIENCE, SPORTS_AND_RECREATION, TELECOMMUNICATIONS, TRANSPORTATION_AND_LOGISTICS,
    TRAVEL_AND_TOURISM, UTILITIES

}